sudo: false

language: scala

jdk:
  - oraclejdk8

script:
  - sbt clean coverage test scalastyle coverageReport && sbt coverageAggregate

before_cache:
  - bash <(curl -s https://codecov.io/bash)
  # Tricks to avoid unnecessary cache updates
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm

# These directories are cached to S3 at the end of the build
cache:
  directories:
    - $HOME/.coursier/cache/
    - $HOME/.ivy2/cache/
    - $HOME/.sbt/boot/
